# Generated by Django 3.1.7 on 2021-03-11 18:52

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_squashed_0004_remove_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120, validators=[products.validators.validate_blocked_words]),
        ),
    ]
