# Generated by Django 3.1.7 on 2021-03-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210311_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('DR', 'Draft'), ('PU', 'Publish'), ('PR', 'Private')], default='DR', max_length=2),
        ),
    ]
