# Generated by Django 3.1.7 on 2021-03-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210312_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
